<MenuScreen>:
    BoxLayout:
        orientation: 'vertical'
        ScreenTitle:
            Title:
                text: 'Menu'
            Logo:
        MenuButton:
            text: 'Translator'
            on_press: root.manager.current = 'translator'
        MenuButton:
            text: 'Konec'
            on_release: app.stop()
        BoxLayout:
            size_hint: 1, .6
        StatusBar:
            size_hint: 1, .1